# Generated by Django 4.0.6 on 2022-08-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_team_address_alter_team_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RaceAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.BigIntegerField()),
                ('team_id', models.BigIntegerField(blank=True)),
                ('lane', models.CharField(max_length=20)),
                ('time', models.TimeField(blank=True)),
            ],
        ),
    ]
