# Generated by Django 4.0.6 on 2022-08-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_race_raceassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceassign',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
