# Generated by Django 4.0.6 on 2022-08-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_team_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceassign',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
