# Generated by Django 4.1 on 2022-08-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_raceassign_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceassign',
            name='time',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
