# Generated by Django 4.1 on 2022-08-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_raceassign_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceassign',
            name='time',
            field=models.FloatField(default=0.0),
        ),
    ]
