# Generated by Django 4.0.6 on 2022-08-31 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_raceassign_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='address',
            field=models.TextField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
