# Generated by Django 4.0.6 on 2022-09-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_team_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('site', models.CharField(max_length=20, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
