# Generated by Django 4.0.6 on 2022-09-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('fname', models.CharField(blank=True, max_length=100)),
                ('lname', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='raceassign',
            name='skipper_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raceassign',
            name='team_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
