# Generated by Django 4.0.6 on 2022-09-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_skipper_raceassign_skipper_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='date',
            field=models.DateField(),
        ),
    ]
