# Generated by Django 4.0.6 on 2023-03-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_team_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('skipper_id', models.BigIntegerField(null=True)),
                ('team_id', models.BigIntegerField(null=True)),
            ],
        ),
    ]
