# Generated by Django 4.0.6 on 2023-04-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_training_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
    ]
