# Generated by Django 4.0.6 on 2023-05-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_training_active_alter_training_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='duration',
            field=models.DecimalField(decimal_places=0, default=90, max_digits=3),
        ),
    ]
