# Generated by Django 4.0.6 on 2023-05-01 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_training_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=5400)),
        ),
    ]
