# Generated by Django 4.0.6 on 2023-05-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_team_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='free_entry',
            field=models.BooleanField(default=False),
        ),
    ]
