# Generated by Django 4.0.6 on 2023-06-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_remove_training_free_entry_team_nofee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='category_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
