# Generated by Django 4.0.6 on 2023-06-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_category_team_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(default='A', max_length=2),
            preserve_default=False,
        ),
    ]
