# Generated by Django 4.0.6 on 2023-06-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_category_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='category_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
