# Generated by Django 4.0.6 on 2023-06-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_alter_category_tag_alter_team_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
