# Generated by Django 5.2.4 on 2025-07-04 19:09

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_alter_team_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(default=content.models.get_default_training_date),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.DurationField(default=content.models.get_default_training_length),
        ),
    ]
